templates:
  - file: "macros.jinja"
    name: "macros"

  - file: "datatypes.h.jinja"
    name: "header_tpl"
    suffix: ".h"
    type: "cc_library_hdrs"

  - file: "datatypes.rs.jinja"
    name: "rust_tpl"
    suffix: ".rs"
    type: "rust_library_srcs"

  - file: "datatypes.cpp.jinja"
    name: "cpp_tpl"
    suffix: ".cpp"
    type: "cc_library_srcs"

  - file: "datatypes.skeleton.cpp.jinja"
    name: "cpp_skeleton_tpl"
    suffix: "_skeleton.cpp"
    type: "cc_skeleton_library_srcs"
