templates:
  - file: "macros.jinja"
    name: "macros"
  - file: "datatypes.h.jinja"
    name: "header_tpl"
    suffix: ".h"
    group: "typeslib_h"
  - file: "datatypes.rs.jinja"
    name: "rust_tpl"
    suffix: ".rs"
    group: "typeslib_rs"
  - file: "datatypes.cpp.jinja"
    name: "cpp_tpl"
    suffix: ".cpp"
    group: "typeslib_cpp"
  - file: "datatypes.skeleton.cpp.jinja"
    name: "cpp_skeleton_tpl"
    suffix: "_skeleton.cpp"
    group: "skeleton_cpp"
